// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYBdMvu65iHXsAJSYm4JRo2rkMP10KcxA',
    appId: '1:453685707747:web:4f20b40bffe78c29b056d6',
    messagingSenderId: '453685707747',
    projectId: 'kayan-34bf0',
    authDomain: 'kayan-34bf0.firebaseapp.com',
    storageBucket: 'kayan-34bf0.appspot.com',
    measurementId: 'G-E7MCDJZHNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0i9iQxpcfSQJ_-08HmsPRVYpuX92mAO0',
    appId: '1:453685707747:android:7353bcfcf8d16978b056d6',
    messagingSenderId: '453685707747',
    projectId: 'kayan-34bf0',
    storageBucket: 'kayan-34bf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEb6YZ1m1R23YKl6gXcqktAjW_IcN_Atc',
    appId: '1:453685707747:ios:c4e04e91a4dc468db056d6',
    messagingSenderId: '453685707747',
    projectId: 'kayan-34bf0',
    storageBucket: 'kayan-34bf0.appspot.com',
    iosClientId: '453685707747-4n50slb1i9le43lp9llktto66lcfc6h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.kayan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEb6YZ1m1R23YKl6gXcqktAjW_IcN_Atc',
    appId: '1:453685707747:ios:c4e04e91a4dc468db056d6',
    messagingSenderId: '453685707747',
    projectId: 'kayan-34bf0',
    storageBucket: 'kayan-34bf0.appspot.com',
    iosClientId: '453685707747-4n50slb1i9le43lp9llktto66lcfc6h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.kayan',
  );
}
